### ISSUE TITLE
Ability to sort based on ownership

### ISSUE THREAD

**Issue by pbirkhol-ni** [ni/reviewboard-userscripts#22]
## Is your feature request related to a problem?

Yes. Review overload. My team gets a lot of reviews (as I'm sure most teams do). In our retrospective, most people expressed wanting to be alerted to the reviews, but also want to be able to sort reviews that they _have_ to review vs reviews where they are optional.

## Describe the solution you'd like

Be able to sort reviews on the reviewboard mainpage based on whether you're an owner, an alternate, or a reviewer. 

## Describe alternatives you've considered

An email rule that flags a reviewboard email if you're an owner.

**Comment by alejandro5042** [comment]
I hear ya! Review overload sucks. It's something that Dev Efficiency and the Software Discipline have been and are still addressing, especially in drivers.

Note however: If you are added to a review as an owner, alternate, or reviewer -- in other words, you're listed in an niconfig file -- your approval is required 100% of the time. Alternatively, you may be removed/declined from the review. Alternatively, a tech lead can "vouch" for the changes and bypass the owner review process (a process that is currently specific to AzDO). Either way, your approval or removal is required for the review to complete. It is further expected that you reply within 24 business hours. All DevCentral Git repos have [tooling](https://ni.visualstudio.com/DevCentral/_wiki/wikis/AppCentral.wiki/6918/PR-Reminder-Emails) to remind reviewers to do their reviews if over a day has passed.

For more info on this policy, [see this doc](https://ni.visualstudio.com/DevCentral/_wiki/wikis/AppCentral.wiki/998/Code-Owner-Handbook).

I also understand that this policy hasn't been communicated equally in teams onboarding to niconfig. I know @zhindes will have more on this topic very soon, including curating the various docs we have on this topic. [Here's](https://nio365.sharepoint.com/sites/SoftwareDiscipline/SitePages/Code-Reviews--What-We-Need-to-Do-Next.aspx) some preliminary comms on this topic.

Because your review is required, sorting the dashboard based on your specific role (owner/alt/reviewer) is not necessary, because all reviews have the same requirement to complete. Furthermore, all reviews at NI have a 24 hour rule.

If you'd like to chat more about the policy, let's sync up on Teams. Afterward, if you believe you still want this feature, let's reopen the issue, easy :)
