### ISSUE TITLE
Change draft review header color to yellow/orange

### ISSUE THREAD

**Issue by alejandro5042** [ni/reviewboard-userscripts#7]
## Is your feature request related to a problem?

Since I recolored submitted reviews to green, there is now a conflict with the existing green banner representing a draft review.

## Describe the solution you'd like

Color the draft review banner yellow.

## Describe alternatives you've considered

Reverting the green back to gray, but it should be green to better match AzDO and societal expectation of what green means (success).

## Additional context

Userscript version: v1.1.10

**Comment by vijaysitaram** [comment]
The draft for a reply within a comment thread is still green, but that's OK since it's localized to the top of the comment thread and should not be confusable with any other workflow context. In fact it may be preferable so the same gold color doesn't blend in too much with the rest of the main UI:

![image](https://user-images.githubusercontent.com/66134815/83530633-97baf480-a4b1-11ea-9f4b-114da6fb7fa1.png)

**Comment by vijaysitaram** [comment]
And a brand new draft (never before published) still appears to use green for unpublished changes, as opposed to yellow signaling attention required:
![image](https://user-images.githubusercontent.com/66134815/83589542-932a2680-a519-11ea-8d9c-290c8afbbe8d.png)

**Comment by alejandro5042** [comment]
In the latest version, I also changed that banner to yellow. Let me know if you see any other color issues!
